# Generated by Django 6.0.4 on 2026-04-18 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('employees', '0001_initial'),
        ('models_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Приглашена'), ('under_review', 'На рассмотрении'), ('approved', 'Утверждена'), ('rejected', 'Отказ'), ('completed', 'Завершено')], default='invited', max_length=20, verbose_name='Статус участия')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='models_app.modelcard', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Участие модели в проекте',
                'verbose_name_plural': 'Участия моделей в проектах',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('project_type', models.CharField(choices=[('casting', 'Кастинг'), ('photosession', 'Фотосессия'), ('show', 'Показ'), ('advertising', 'Реклама')], default='casting', max_length=20, verbose_name='Тип проекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('new', 'Новый'), ('in_progress', 'В работе'), ('completed', 'Завершен'), ('canceled', 'Отменен')], default='new', max_length=20, verbose_name='Статус')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Бюджет / выручка')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='clients.client', verbose_name='Заказчик')),
                ('models', models.ManyToManyField(blank=True, related_name='projects', through='projects.Participation', to='models_app.modelcard', verbose_name='Модели')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='employees.employeeprofile', verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.AddField(
            model_name='participation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='projects.project', verbose_name='Проект'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('project', 'model'), name='unique_model_participation_per_project'),
        ),
    ]
