# Generated by Django 6.0.4 on 2026-04-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('director', 'Директор агентства'), ('booker', 'Букер'), ('scout', 'Скаут'), ('admin', 'Системный администратор')], default='scout', max_length=20, verbose_name='Роль')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Дата приема')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль сотрудника',
                'verbose_name_plural': 'Профили сотрудников',
                'ordering': ['user__last_name', 'user__first_name', 'user__username'],
            },
        ),
    ]
