# Generated by Django 6.0.4 on 2026-04-18 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('height', models.PositiveSmallIntegerField(verbose_name='Рост, см')),
                ('bust', models.PositiveSmallIntegerField(verbose_name='Объем груди, см')),
                ('waist', models.PositiveSmallIntegerField(verbose_name='Талия, см')),
                ('hips', models.PositiveSmallIntegerField(verbose_name='Бедра, см')),
                ('shoe_size', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Размер обуви')),
                ('hair_color', models.CharField(blank=True, max_length=50, verbose_name='Цвет волос')),
                ('eye_color', models.CharField(blank=True, max_length=50, verbose_name='Цвет глаз')),
                ('experience', models.TextField(blank=True, verbose_name='Опыт работы / описание')),
                ('category', models.CharField(choices=[('top', 'Top-model'), ('new_face', 'New face'), ('commercial', 'Commercial')], default='new_face', max_length=20, verbose_name='Категория')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('archived', 'В архиве'), ('on_contract', 'На контракте')], default='active', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='models/main/', verbose_name='Главное фото')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_model_cards', to=settings.AUTH_USER_MODEL, verbose_name='Кем добавлена анкета')),
            ],
            options={
                'verbose_name': 'Анкета модели',
                'verbose_name_plural': 'Анкеты моделей',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ModelPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='models/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=150, verbose_name='Подпись')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='models_app.modelcard', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Фото модели',
                'verbose_name_plural': 'Фото моделей',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
